apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
spec:
  targetNamespaces:
  - openshift-dedicated-admin
